### PR TITLE
Add machinable experiments

### PR DESCRIPTION
**Pull request by frthjf**
Adds an alternative, more high-level interface for running the simulator using [machinable](https://machinable.org)

- [x] complete replication of running the microcircuit model
- [x] fix issue of auto-merging the H5 file for the simulator
- [x] enable input generation from MiV-OS spike train
- [x] add slurm default resources and example
- [x] add example to documentation

### CODE REVIEW

**Comment by skim0119** [comment]
I'll start reviewing this

**Comment by frthjf** [comment]
Cool, thanks! Just finished the docs, so it's ready for review now.

**Review by iraikov — COMMENTED** [review]
Thanks, Frithjof! My only comment so far is that it looks like it is still the case that the mechanisms are compiled in the site-packages directory. Does the code currently support mechanisms and templates that are not part of the miv_simulator package? And can we remove the mechanisms and template files from miv_simulator?

**Comment by frthjf** [comment]
Good point, adjusting the directories is supported but I agree that it would be better to just remove the defaults from the package source and instead let the user provide them. Otherwise, it's hard to know and control what files are being used. I don't remember, does the click CLI rely on the included files by default? If not, I guess I can just remove them in this PR. Alternatively, we can merge this and then I can delete the files for both machinable and the click-CLI in a follow up.

**Comment by iraikov** [comment]
The CLI does not rely on the included files, but it does not yet have an option to specify a mechanisms directory. So I think you can go ahead and remove the files in this PR and merge, and I will separately check for any issues with finding and compiling mechanisms.

**Comment by skim0119** [comment]
It all looks good to me. Sorry for the delay, I had some issues building the documentation. It was an issue with my local machine.

**Review by skim0119 — APPROVED** [review]

**Pull request merged**
