### PR TITLE
Change directories for default morphology and mechanisms

### LINKED ISSUE #36: Allow overrides for default mechanisms and morphology
Like with the YAML configuration, there should be a way to progressively override the default mechanism and morphology without duplication all of the configuration files. For example, a user might change the `cat.mod` mechanism in their code base, while still falling back on the default mechanism in all other cases.

Proposed implementation:
- Copy defaults into tmp directory within venv, merge in user files to potentially override defaults
- Compile dll and return location of tmp directory to be used instead of user directory
- Compute a directory hash of user directory (likely using a [suitable subprocess call](https://stackoverflow.com/questions/545387/linux-compute-a-single-hash-for-a-given-folder-contents)) to avoid unnecessary recompilation

### PR DESCRIPTION
**Pull request by frthjf**
- [x] Renames `datasets/*.swc` directory to `morphology` to avoid confusion with H5 datasets
- [x] Allow to pass arbitrary directories to mechanism compilation

This is just an intermediate step to resolve #36.

### CODE REVIEW

**Comment by skim0119** [comment]
Looks good. While we are on this topic, I'm thinking would it be possible to add `compile_and_load` step before `run-network` cli-command? We might need an extra argument to accept additional morphology files.

**Comment by iraikov** [comment]
Thanks, Frithjof. I think the mechanism directory changing feature is sensible; he only thing to keep in mind that it used to cause problems on non-Linux platforms, so we need to test it at least on Mac OS. As for the .swc files, those are actually specific to the CA1 model from where this code was derived, so it makes more sense to move them to the MiV microcircuit model repository. The only "default" morphology that would make sense in this case is some kind of abstract structure that consists of e.g. only soma and single dendrite (the so-called ball-and-stick morphology), in other words it is not specific to a particular neuron type.

**Review by iraikov — APPROVED** [review]

**Comment by frthjf** [comment]
Thanks for the feedback. In that case, would it perhaps be better to just remove the `morphology/*.swc` files all together and just make them part of the Cases repository? We could add a mandatory argument to the CLI to specify the location of the swc files. For the mechanism, I can see if I can add a test for macOS - my guess is that the dll just ends up in a different subfolder.

**Review by skim0119 — APPROVED** [review]

**Comment by skim0119** [comment]
I'll merge this PR for now. I made a separate issue regarding the placement for `morphology` files. #39

**Pull request merged**
